# Generated by Django 4.1.5 on 2023-03-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('P', 'physical'), ('V', 'virtual'), ('B', 'both')], max_length=1)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('published', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
