# Generated by Django 4.1.5 on 2023-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published_alter_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='rem'),
            preserve_default=False,
        ),
    ]
